version: '3'

services:
  resume-frontend:
    build:
      context: ./ResumeBuilderAngular
      dockerfile: Dockerfile

    ports:
      - 80:80

    depends_on:
      - backend

  resume-backend:
    build:
      context: ./ResumeBuilderBackend
      dockerfile: Dockerfile

    ports:
      - 4292:4292
