version: '3'

services:
  resume_frontend:
    build:
      context: ./ResumeBuilderAngular
      dockerfile: Dockerfile

    ports:
      - 80:80

    depends_on:
      - 'resume_backend'

  resume_backend:
    build:
      context: ./ResumeBuilderBackend
      dockerfile: Dockerfile

    ports:
      - 4292:4292
