apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendbuilder # Name of the deployment in K8s
spec:
  selector:
    matchLabels:
      app: app_backend
  template:
    metadata:
      labels:
        app: app_backend
    spec:
      containers:
        - name: app_backend
          image: resumeai-resume_backend
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 4292
